@host = http://localhost:8080

GET {{host}}/api/status
Accept: application/json

###

GET {{host}}/api/orders
Accept: application/json

###

GET {{host}}/api/orders/by-reference/DEMO-1001
Accept: application/json

###

GET {{host}}/api/admin/users
Accept: application/json

###

POST {{host}}/api/orders
Content-Type: application/json

{
  "customerEmail": "new.customer@example.test",
  "customerName": "New Customer",
  "externalReference": "DEMO-1003",
  "amount": 99.00
}
